name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [16.x, 17.x, 18.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: yarn install

            - name: Build Angular App
              run: yarn build
